on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: 0 3 1 * *


name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    
    # General set-up
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install libcurl4-openssl-dev
        run: sudo apt-get install -y libcurl4-openssl-dev

      - name: Install libharfbuzz-dev libfribidi-dev libtiff5-dev
        run: sudo apt install libharfbuzz-dev libfribidi-dev libtiff5-dev
        

    # R and {renv} set-up
      - uses: r-lib/actions/setup-r@v2

      - name: Set RENV_PATHS_ROOT
        shell: bash
        run: |
          echo "RENV_PATHS_ROOT=${{ runner.temp }}/renv" >> $GITHUB_ENV
      
      - name: Install and activate renv
        run: |
          install.packages("renv")
          renv::activate()
        shell: Rscript {0}
        
      - name: Restore Renv package cache
        if: ${{ inputs.bypass-cache != 'true' }}
        uses: actions/cache@v4
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-${{ hashFiles(format('{0}/renv.lock', inputs.working-directory)) }}
          restore-keys: ${{ steps.get-version.outputs.os-version }}-${{ steps.get-version.outputs.r-version }}-${{inputs.cache-version }}-
        
      - name: Install renv dependencies
        run: renv::restore()
        shell: Rscript {0}
        
    

    # Quarto set up and publishing
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
